import { IState } from '../models';

export const States: { [key: string]: IState } = {
  AP: { name: 'Andhra Pradesh', uf: 'AP' },
  AR: { name: 'Arunachal Prades', uf: 'AR' },
  AS: { name: 'Assam', uf: 'AS' },
  BR: { name: 'Bihar', uf: 'BR' },
  CG: { name: 'Chhattisgarh', uf: 'CG' },
  GA: { name: 'Goa', uf: 'GA' },
  GJ: { name: 'Gujarat', uf: 'GJ' },
  HR: { name: 'Haryana', uf: 'HR' },
  HP: { name: 'Himachal Pradesh', uf: 'HP' },
  JH: { name: 'Jharkhand', uf: 'JH' },
  KA: { name: 'Karnataka', uf: 'KA' },
  KL: { name: 'Kerala', uf: 'KL' },
  MP: { name: 'Madhya Pradesh', uf: 'MP' },
  MH: { name: 'Maharashtra', uf: 'MH' },
  MN: { name: 'Manipur', uf: 'MN' },
  ML: { name: 'Meghalaya	', uf: 'ML' },
  MZ: { name: 'Mizoram', uf: 'MZ' },
  NL: { name: 'Nagaland', uf: 'NL' },
  OD: { name: 'Odisha', uf: 'OD' },
  PB: { name: 'Punjab', uf: 'PB' },
  RJ: { name: 'Rajasthan', uf: 'RJ' },
  SK: { name: 'Sikkim', uf: 'SK' },
  TN: { name: 'Tamil Nadu	', uf: 'TN' },
  TS: { name: 'Telangana', uf: 'TS' },
  TR: { name: 'Tripura', uf: 'TR' },
  UP: { name: 'Uttar Pradesh', uf: 'UP' },
  UK: { name: 'Uttarakhand', uf: 'UK' },
  WB: { name: 'West Bengal', uf: 'WB' },
};
